### ISSUE TITLE
Error while activating plugin - timed out waiting for plugin

### ISSUE THREAD

**Issue by krisgermann** [moussetc/mattermost-plugin-giphy#11]
I'm using a self-hosted Mattermost installation on Ubuntu 17.10, Mattermost version 4.4.0  (4.4.3) with a MySQL backend.

I'm getting the following error when uploading v0.2.0

 unable to start plugin: com.github.moussetc.mattermost.plugin.giphy: timed out waiting for plugin

**Comment by moussetc** [comment]
The v0.2.0 is not compatible with Mattermost 5.1 and below, but actually, your Mattermost version is not supported by the plugin *at all* since slash command support for plugins was added in Mattermost 4.6.
