### ISSUE TITLE
Unable to get GIF URL

### ISSUE THREAD

**Issue by lvictorino** [moussetc/mattermost-plugin-giphy#15]
When trying to request a gif via `/gif` command... I get a red message telling `Unable to get GIF URL`. What should I do? Where should I look?
Thanks for your help.

**Comment by moussetc** [comment]
Please provide the following data:
1. Mattermost server version
2. Plugin version
3. Mattermost server OS
4. Is the Mattermost server behind a proxy?
4. If there's a proxy, has the environment variables been setted as [per documentation](https://docs.mattermost.com/install/outbound-proxy.html)
5. Is the Mattermost [image proxy](https://docs.mattermost.com/administration/image-proxy.html) currently enabled?
6. **What is the error message that appears in the System Console logs?**

**Comment by lvictorino** [comment]
Could it be because of the default API Token?

**Comment by moussetc** [comment]
Look, without the actual log, I can't help you ;) The error message you gave is the generic message displayed to users, and can cover multiple issues, such as the one described in #13 .
 
But yeah, anyway, as mentioned in the plugin configuration manual you should get your own api key.

**Comment by corumj** [comment]
I am experiencing this issue as well - 
Mattermost Version 5.10.0
Plugin version: v0.2.0-alpha (mattermost-plugin-giphy-linux-amd64.tar.gz)
Mattermost is running with Docker-Compose which according to the app Dockerfile is using Alpine 3.9
Image proxy is not enabled
System logs show this error:
{"level":"error","ts":1557762061.8685744,"caller":"mlog/log.go:172","msg":"Unable to get GIF URL","path":"/api/v4/commands/execute","request_id":"333zzxjcy3b75pxtpshai75itc","ip_addr":"10.1.200.25","user_id":"kmcstqz9j783uk8etub8tjxhma","method":"POST","err_where":"Giphy Plugin","http_code":400,"err_details":"Error HTTP status 429: 429 Unknown Error"}

**Comment by moussetc** [comment]
@corumj Are you by chance using the default public API key for Giphy? That might explain the *429 Too Many Requests* error.

**Comment by corumj** [comment]
Yes, I left everything as a default, though at the moment I am the only user of our Mattermost server (we're in the investigating options stage...) so I've only done two /gif tests

**Comment by corumj** [comment]
Signed up real quick and got my own giphy API key- can confirm that that fixed it!

**Comment by moussetc** [comment]
I kept the default API key as default because it allowed potential users to test the plugin quickly, but it seems that it's not working as well lately, so I might remove it altogether. Thanks for your detailed report!

**Comment by moussetc** [comment]
@lvictorino Did setting your own API work?

**Comment by moussetc** [comment]
Closing this obsolete issue now.
