### ISSUE TITLE
Shuffle not working

### ISSUE THREAD

**Issue by LoganxDev** [moussetc/mattermost-plugin-giphy#20]
The /gifs functionality that allows for shuffling of gifs doesn't appear to be working for my Mattermost install. When running the gifs slash command a preview pops up in the chat but where I would think the shuffle button would be is a formatted text box with a small vertical blue line.

Is this what "(breaking plugin API change)" refers to in the README?

Mattermost version: 5.3.1
Plugin Version: 1.1.0

**Comment by jjtolton** [comment]
I'm having the same issue. Additional technical information:

![image](https://user-images.githubusercontent.com/10394611/71698323-23a4e500-2d89-11ea-913a-df8597c3ecb6.png)

```
POST /api/v4/posts/******/actions/****** HTTP/1.1
Host: *****
Connection: keep-alive
Content-Length: 722
Sec-Fetch-Mode: cors
Origin: https://********
X-CSRF-Token: *****
Accept-Language: en
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Content-Type: text/plain;charset=UTF-8
X-Requested-With: XMLHttpRequest
DNT: 1
Accept: */*
Sec-Fetch-Site: same-origin
Accept-Encoding: gzip, deflate, br
Cookie: ajs_group_id=null; ajs_user_id=%22musn754jtjrfbcux66d8ckr6po%22; ajs_anonymous_id=%2200000000000000000000000000%22; ajs_user_id=%22musn754jtjrfbcux66d8ckr6po%22; ajs_group_id=null; ajs_anonymous_id=%2200000000000000000000000000%22; MMAUTHTOKEN=*******; MMUSERID=*******; MMCSRF=*******

```json 
{"id":"api.post.do_action.action_integration.app_error","message":"Action integration error","detailed_error":"","request_id":"********","status_code":400}
```

**Comment by moussetc** [comment]
@LoganxDev Your Mattermost version is simply too old to be compatible with the shuffle feature (only in Mattermost 5.10+ can one put buttons that works on ephemeral (private) messages, which is required for the shuffle feature). It is advised to use the Compatibility section of the README to know the recommended plugin version for your Mattermost installation.

I'll update the README to indicate that the shuffle feature is not available for older Mattermost/plugin versions.

@jjtolton please also check your Mattermost version compatibility. If this isn't a compatibility issue, please open another github issue.

Le 11 déc. 2019 à 01:55, à 01:55, Logan Lasiter <notifications@github.com> a écrit:

**Comment by jjtolton** [comment]
@moussetc we're running v5.15.0 (the GCP managed bitnami mattermost team edition), so I'll open a new issue.

**Comment by jjtolton** [comment]
https://github.com/moussetc/mattermost-plugin-giphy/issues/21

**Comment by LoganxDev** [comment]
@moussetc Thanks for reply, I'll try an update on the mattermost version.
