### ISSUE TITLE
Add to Plugin Marketplace 

### ISSUE THREAD

**Issue by hanzei** [moussetc/mattermost-plugin-giphy#23]
Hi @moussetc,

Thanks for writing and continuing to maintain this plugin :+1: 

It's a quite popular one and would be great to have on the Plugin Marketplace. Would you be interested on submitting your plugin to the Plugin Marketplace? You can find the process [here](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/).

**Comment by moussetc** [comment]
Hi, thank you for this encouraging message. I'll look into the marketplace admission process but I might wait for it to be a little more mature (ex: the requirements mention a `release_notes_url` field that is not in the [current manifest doc](https://developers.mattermost.com/extend/plugins/manifest-reference/), nor is used in the JIRA or Github plugin).

**Comment by hanzei** [comment]
The process is indeed quite new. Good catch on `release_notes_url`. I've submitted https://github.com/mattermost/mattermost-developer-documentation/pull/589 to add it to the docs.

Did you find other issue in the process document?

**Comment by moussetc** [comment]
Thank you. Some more remarks (english is not my main language so these are from the pov of someone who needs a lot of clarity ;) ):
- The § for "Process for Updating Community Plugin to the Marketplace " refer to the GitHub Issue template for **new** plugins.
- It's unclear to me what step 2 "The owner forks the community repository under the Mattermost GitHub organization as a private fork so the existing build tools for releasing new plugin versions can be used. " refers to. Maybe add a link to the GitHub repo? This remark might be made moot by the answer to the following question:
-  Either I've misunderstood the notion of _owner_, or the name is a bit confusing. It is the maintainer of the plugin or is it a person from Mattermost whose role is "to guide you through the review process"? Reflecting on this, it's probably be the second meaning, but only at the 3d time did I read fully the definition of _owner_ for the purpose of the doc, as I naturally interpreted _owner_ as the plugin's maintainer.
- Regarding the changelog URL, is a link the the plugin's repo Release page enough? If not, does as CHANGELOG.md which content is a link to the Releases page enough (like for the Github plugin)?

**Comment by hanzei** [comment]
1. Good catch :+1: I will update the docs.
2. With my answer in 3. is this more clear?
3. Yes, it's the second meaning. At Mattermost `owner` is used for staff members that take ownership of a specific area. But I see that this is not common knowledge and the name might be confusing. Would it be more clear if  https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/#process-for-adding-a-community-plugin-to-the-marketplace would mention that the `owner` is a staff member? Do you have alternative suggestion for `owner`?
4. Yes, GitHub release pages are definitely fine. Will update the docs to point this out.

**Comment by hanzei** [comment]
I've submitted https://github.com/mattermost/mattermost-developer-documentation/pull/604 for update the docs

**Comment by moussetc** [comment]
Thank you for the update and answers.
Regarding the *owner* term, it would indeed be better to mention it's a staff member. I don't really have a better one-word term for it though, the best I can think of is _handler_ but I'm not sure it's a correct translation from the word I have in mind :sweat_smile:

**Comment by moussetc** [comment]
The version 1.3.0 is available in the Mattermost marketplace 🎉
