### ISSUE TITLE
gifs submission does used thread

### ISSUE THREAD

**Issue by hanzei** [moussetc/mattermost-plugin-giphy#29]
**Describe the bug**
The gif posted when clicking `Send` is not posted in a thread.

**To Reproduce**
1. Open a thread
2. Type `/gifs kitten`
3. Click `Send`
4. See kitten image gets posted in the main panel

**Expected behavior**
Kitten image gets posted in the LHR as part of the thread

**Screenshots**
![Screenshot from 2020-04-28 09-16-49](https://user-images.githubusercontent.com/16541325/80458416-0942d880-8931-11ea-9ea9-107fcdbeed4b.png)

![Screenshot from 2020-04-28 09-16-56](https://user-images.githubusercontent.com/16541325/80458425-0ba53280-8931-11ea-90f9-bd3bc3eeca53.png)

**Mattermost information**
- server version: server: `b29b70da0910bfa707b152feebcfefe198f49424`. webapp: `c5d504965e9ee81e515c58197b2739b34259da60`
- client version: Chromium
- plugin version: `v1.2.1`

**Comment by moussetc** [comment]
Nice catch, fixed&released in v1.3.0
