### ISSUE TITLE
Ability to force /gifs

### ISSUE THREAD

**Issue by Renari** [moussetc/mattermost-plugin-giphy#30]
We've had a few inappropriate gifs that have been posted on our server, would it be possible to force `/gifs` functionality so that everyone has to self moderate before they are sent to everyone?

**Comment by moussetc** [comment]
That would be be to add a configuration option to allow the Mattermost administrator to deactivate the `/gif` command, leaving only the `/gifs`, is that right?
(If you're using Giphy, there's a rating filter you can use, but it is not available for Gfycat sadly.)

**Comment by Renari** [comment]
Yeah that would work.

**Comment by moussetc** [comment]
As the default provider (Gfycat) does not have rating filtering, and as I feel it's better to preview a semi-random result before posting publicly, there's now, as of version 1.4.0, an option to have only one `/gif` command, with preview enabled.
