### ISSUE TITLE
Feature request:As a admin I want to be able to make sure a GIF does only run once.

### ISSUE THREAD

**Issue by prosanhive** [moussetc/mattermost-plugin-giphy#35]
Feature request

As a admin I want to be able to make sure a GIF does only run once.

Admin option for enabling number of cycles e.g 0

**Comment by moussetc** [comment]
Hi, this will not be done at plugin level, but rather at Mattermost client level. There's a feature request to the Mattermost team on this subject, albeit with a non configurable number of cycles: mattermost/mattermost-server#15399
