### ISSUE TITLE
Giphy requires proper attribution

### ISSUE THREAD

**Issue by tjdownes** [moussetc/mattermost-plugin-giphy#38]
In order to get a production key for Giphy, they require attribution per their terms. 

"Thanks for your interest in using our API.. Also, per our terms of service, we require all users of our API to include the approved "Powered by GIPHY" attribution. It looks as though your attribution is currently in plain text, which is not compliant with our terms. You can download approved assets here: http://www.google.com/url?q=http%3A%2F%2Fgiphymedia.s3.amazonaws.com%2Fgiphy-attribution-marks.zip&sa=D&sntz=1&usg=AFQjCNH2vioX4nvSrL6iR2kuB_WG-85VLA Once you make that fix, can you please edit your application and attach a video capture of the user experience for adding GIFs in your app?"

**Comment by tjdownes** [comment]
It appears this is being addressed by #37

**Comment by moussetc** [comment]
The new 2.1.0 version of the plugin embarks the modifications asked by GIPHY. The version is available now for direct download on the [Releases](https://github.com/moussetc/mattermost-plugin-giphy/releases) pages, and will be soon available in the Mattermost Marketplace, pending Mattermost approval.

**Comment by moussetc** [comment]
FYI the release that fixes this issue has been made available on the marketplace this August.
