### ISSUE TITLE
Gif not randomized for same keyword

### ISSUE THREAD

**Issue by pe1uca** [moussetc/mattermost-plugin-giphy#41]
Observation:
The command only retrieves the same gif each time is called for the same keyword.

Improvement:
Randomize which gif to use instead of hardcoded `[0]`

The issue comes from these lines
https://github.com/moussetc/mattermost-plugin-giphy/blob/93497e9c1cfc4caf0b7610f1e52d2149390283ad/server/internal/provider/gfycat.go#L86
https://github.com/moussetc/mattermost-plugin-giphy/blob/93497e9c1cfc4caf0b7610f1e52d2149390283ad/server/internal/provider/giphy.go#L116
https://github.com/moussetc/mattermost-plugin-giphy/blob/93497e9c1cfc4caf0b7610f1e52d2149390283ad/server/internal/provider/tenor.go#L118

(was only able to test if with gfycat since it is what our MM uses)

**Comment by moussetc** [comment]
Addendum: actually we have the same issue with Tenor V2: while Giphy and Tenor V1 (which was put out of order) provide a true /random API (even though it has limited options, for example it does not support language), Tenor V2 only allows to randomize the search result...

**Comment by moussetc** [comment]
In release 3.0.0, you can configure the plugin to return random results. For Giphy, we use the provided random endpoint, but for Tenor&Gfycat, we pseudo-randomize the current page of results (meaning that you will always have the same first 10 or 20 GIFs, although not in the same order, and you will need to shuffle through to get to the next page of fresh results).
