### ISSUE TITLE
Feature request: Support image collapsing

### ISSUE THREAD

**Issue by mickmister** [moussetc/mattermost-plugin-giphy#42]
With an uploaded image or an image linked by URL, the user is able to minimize the image via collapsing arrows to the top right of the image. Is it possible for the plugin to do this as well?

Expanded
<img width="400" src="https://user-images.githubusercontent.com/6913320/111848312-297cdc80-88e1-11eb-8e35-fe68b5f4db4a.png"/>

Collapsed
<img width="400" src="https://user-images.githubusercontent.com/6913320/111848319-2e419080-88e1-11eb-8e70-6e919fbdf191.png"/>

**Comment by moussetc** [comment]
Making embedded images collapsible must be done by the Mattermost clients, not by the plugin, but in the meanwhile, you can configure the plugin to display the link as a full URL, which makes it collabsible, with the option _Collapsable image preview_ (it requires links preview to be activated on your M server)
See #12 for more details.
