### ISSUE TITLE
Cannot leave Content Rating blank

### ISSUE THREAD

**Issue by bbodenmiller** [moussetc/mattermost-plugin-giphy#45]
Help text says: "Choose the MPAA-style rating or leave empty to disable filtering."

But it's not possible to leave blank

**Comment by moussetc** [comment]
Thanks for the report! The fix will be included in the next release (TBD). In the meanwhile:
- if you're using Gfycat, content rating is not used anyway
- if you're using Giphy or Tenor, using the R rating is equivalent to no filtering.
