### ISSUE TITLE
Giphy attribution looks slightly out of place when Collapsible image preview is enabled

### ISSUE THREAD

**Issue by DHaussermann** [moussetc/mattermost-plugin-giphy#46]
**Describe the bug**
The Giphy attribution (introduced in `v2.1.0`) looks slightly out of place (bottom image) when it is placed on the right of the image URL. As shown by the top image, this only occurs when the URL is also shown. 

It may look better to put the attribution on the left or wrap it it down to the next line.

![image](https://user-images.githubusercontent.com/35588783/127046055-d5e6ea1c-34d6-4679-be1f-1729ea5061ad.png) 

**To Reproduce**
1. Install and enable `v2.1.0`
2. Set _Display the GIF as:_ to _Collapsible image preview_ 
3. Set provider to `GIPHY`
4. Save
5. Post a gif

**Expected behavior**
It may look better to put the attribution on the left or wrap it it down to the next line.

**Comment by moussetc** [comment]
Thanks for the report.
Fix is available in version 2.1.1 of the plugin (not yet available in the marketplace, refer to [this PR](https://github.com/mattermost/mattermost-marketplace/issues/236) to know when it is officially released in the marketplace).
