### ISSUE TITLE
In isolated cases, seemingly based on number of results Gfycat actions become non-functional

### ISSUE THREAD

**Issue by DHaussermann** [moussetc/mattermost-plugin-giphy#47]
**Describe the bug**
In some cases when using Gfycat. the post actions for `Cancel`, `Shuffle` and `Send` become non functional and the gif can't be posted or canceled.   

This does not seem to occur when many results are available to shuffle through. 

This is not a regression from the pervious release.

**To Reproduce**
1. Install and enable Giphy Plugin
2. Set provider to Gfycat
3. Set _Force GIF preview before posting_ to _True_
3. Save and switch to user side
4. Type _/gif pamplemousse_ (no need to set Language to French in plugin settings) and post
**Observed** 
- The buttons in the preview become non-functional when you click them.
- The error log shows:
```
{"level":"dpanic","ts":1627328100.593736,"caller":"zap/sugar.go:185","msg":"Ignored key without a value.","plugin_id":"com.github.moussetc.mattermost.plugin.giphy","ignored":"<nil>"}
{"level":"warn","ts":1627328100.5937111,"caller":"mlog/sugar.go:29","msg":"Could not parse PostActionIntegrationRequest: Missing cursor from action request context","plugin_id":"com.github.moussetc.mattermost.plugin.giphy"}
``` 

**Expected behavior**
`Cancel`, `Shuffle` and `Send` work normally.

**Comment by moussetc** [comment]
Thanks for the report.
Fix is available in version 2.1.1 of the plugin (not yet available in the marketplace, refer to [this PR](https://github.com/mattermost/mattermost-marketplace/issues/236) to know when it is officially released in the marketplace).

**Comment by deseven** [comment]
@moussetc looks like the release never got through, can you please at least make a release for manual installation?

**Comment by moussetc** [comment]
@deseven The Marketplace release has been stuck in limbo for months now (waiting for QA from MM team, the developper review and security review have both been already approved though) and I'm not optimist about it moving anytime soon...

The good news is that you can still use the releases packages that i build&publish myself on GitHub: just download the tar.gz of the pre-release 2.1.1 
https://github.com/moussetc/mattermost-plugin-giphy/releases/tag/v2.1.1 and follow the installation instructions from the README.

**Comment by deseven** [comment]
@moussetc ah, sorry, I didn't see it because pre-releases don't show on the main repo page :( Thank you!
