### ISSUE TITLE
Feature Request: Move Attribution To Picker

### ISSUE THREAD

**Issue by msklywenn** [moussetc/mattermost-plugin-giphy#60]
Hello,

I just read giphy's API terms of service and I don't see anywhere that *every single post* should include a "powered by giphy" attribution. It only says the app must display that there is attribution somewhere in it. Even the configuration window would be enough but that seems a bit unfair, so I kindly ask that the attribution only appears in the gif picker. (If the gif picker is not active, it then ends up in the message directly, as it is now)

Also, I think it would be cleaner if the command didn't show up in the message either. It could be visible as alt-text to the gif?

Best regards,

**Comment by moussetc** [comment]
Hi, 
thank you for the suggestions. 
Removing the attribution message on the final GIF post will be done in the next release (release date to be decided).
I'm not sold on removing the command, however. I like knowing the intent for a GIF  (especially when posted randomly without picker), and alt-text is not accessible on mobile.
