### ISSUE TITLE
Tenor V2 API support

### ISSUE THREAD

**Issue by KrolikowskiK** [moussetc/mattermost-plugin-giphy#66]
Does this plugin support new Tenor API? I tried using V2 API key and got 403 Forbidden response. Wondering if it is just me or the plugin.

**Comment by moussetc** [comment]
Depends on your plugin version. TENOR API V2 is suported since [2.1.2](https://github.com/moussetc/mattermost-plugin-giphy/releases/tag/v2.1.2)
