### ISSUE TITLE
How to choose a gif ?

### ISSUE THREAD

**Issue by florianproxi** [moussetc/mattermost-plugin-giphy#8]
Hello, I managed to install the plugin but it returns a single gif without I can select one that I find more relevant. Is this normal?

**Comment by moussetc** [comment]
Hi, I'm afraid it's completely normal as, of yet, the 'preview and choose' functionality has not been implemented (cf README).

**Comment by moussetc** [comment]
To expand on that, the way I saw it was to post an ephemeral (private) message  with shuffle/post buttons which would then post a public message. But according to the doc the buttons won't work right now for ephemeral messages, so I'm kinda waiting for [this issue to be resolved](https://mattermost.atlassian.net/browse/MM-10516).

But! You might be interested in the soon-to-be Mattermost Release that will include [Gfycat integration ](https://github.com/mattermost/mattermost-webapp/pull/1367). So keep an eye on that one!

**Comment by piotr-wegert** [comment]
Hello @moussetc, looks like https://mattermost.atlassian.net/browse/MM-10516 has been resolved now. Any chance the preview function gets picked in the near future?

**Comment by moussetc** [comment]
There's a lot of chance for that since I started working on it yesterday, right after the danse of joy after reading the MM 5.10 changelog.
I can't give an estimate for a release date, but it's definitively in the works :)

I'm not sure if I'm going to go for a "shuffle" or a "select between multiple choices" solution yet, any opinion in that?

**Comment by piotr-wegert** [comment]
Great news :)

As for the option I'd personally lean towards shuffle.

**Comment by moussetc** [comment]
Shuffle is now available for the plugin version compatible with Mattermost 5.10 and up.
